Implement backtab for tcell widgets
mum4k/termdash pull request #362
Opened 2024-01-27 22:38 UTC by spacez320

This implements "Backtab" (a.k.a. Shift+Tab) as a supported keystroke for tcell widgets. Uses backtab in a few tests and demos as makes sense.

2024-01-28 17:49 UTC, spacez320 commented
Closes https://github.com/mum4k/termdash/issues/360

2024-01-29 19:20 UTC, mum4k requested changes
Looks great, thank you @spacez320.

Please remove the binary file `widgets/textinput/formdemo/formdemo` from the PR. Meanwhile I will verify that all the tests pass and we should be good to go.

2024-01-29 20:05 UTC, spacez320 commented
@mum4k Removed, sorry about that, and thanks for looking.

2024-01-29 20:11 UTC, mum4k approved these changes
Thank you for the contribution!

2024-01-29 20:12 UTC, merged